"""Build the per-segment transcripts and the video table from the YouTube playlist.

Inputs (downloaded with yt-dlp, see README):
  materials/playlist.json                 yt-dlp --flat-playlist -J <playlist>
  materials/transcripts/raw/NNN-<id>.en-orig.json3   auto-captions, one file per video
Outputs:
  materials/videos.csv                    index, lecture, part, lecture title, part title, id, duration
  materials/transcripts/LXX-PYY.txt       clean text, one line per ~20 s, "m:ss" local time
  lecture-notes/videos.tex                \\tsvideo{L@P}{id} table read by the preamble (\\ts links)
"""
import csv
import glob
import json
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MAT = os.path.join(ROOT, 'materials')
LINE_SECONDS = 20


def mmss(ms):
    s = int(ms // 1000)
    return f'{s // 60}:{s % 60:02d}'


def caption_lines(path):
    """json3 auto-captions -> [(start_ms, text)], words grouped in ~LINE_SECONDS chunks."""
    words = []
    for ev in json.load(open(path, encoding='utf8')).get('events', []):
        for seg in ev.get('segs', []):
            w = seg['utf8'].strip()
            if w:
                words.append((ev['tStartMs'] + seg.get('tOffsetMs', 0), w))
    lines, start, buf = [], None, []
    for t, w in words:
        if start is None:
            start = t
        buf.append(w)
        if t - start >= LINE_SECONDS * 1000:
            lines.append((start, ' '.join(buf)))
            start, buf = None, []
    if buf:
        lines.append((start, ' '.join(buf)))
    return lines


def main():
    entries = json.load(open(os.path.join(MAT, 'playlist.json'), encoding='utf8'))['entries']
    rows = []
    for i, e in enumerate(entries, 1):
        m = re.match(r'MOOC \| Lec (\d+): (.+?) \| Part (\d+): (.+)$', e['title'])
        rows.append(dict(index=i, lecture=int(m[1]), part=int(m[3]), lecture_title=m[2].strip(),
                         part_title=m[4].strip(), id=e['id'], duration=int(e['duration'])))

    # self-checks: 192 segments, lectures 1..22, parts 1..n without gaps, Lec 1 = 55:16 of the
    # concatenated transcript (where Lec 2 starts in transcript-lecture-1to6.txt)
    assert len(rows) == 192
    lectures = sorted({r['lecture'] for r in rows})
    assert lectures == list(range(1, 23)), lectures
    for L in lectures:
        parts = [r['part'] for r in rows if r['lecture'] == L]
        assert parts == list(range(1, len(parts) + 1)), (L, parts)
    lec1 = sum(r['duration'] for r in rows if r['lecture'] == 1)
    assert abs(lec1 - (55 * 60 + 16)) <= 5, lec1

    # playlist error: the ColumbiaLearn video for L19.4 is a copy of L19.5; use the re-upload of the
    # right segment (transcribed by tools/whisper_segments.py, so its transcript is not regenerated here)
    OVERRIDE = {(19, 4): ('eZk9A6Pw10g', 179)}
    for r in rows:
        if (r['lecture'], r['part']) in OVERRIDE:
            r['id'], r['duration'] = OVERRIDE[(r['lecture'], r['part'])]
            r['override'] = True

    with open(os.path.join(MAT, 'videos.csv'), 'w', newline='', encoding='utf8') as f:
        w = csv.DictWriter(f, fieldnames=list(rows[0]), extrasaction='ignore')
        w.writeheader()
        w.writerows(rows)

    with open(os.path.join(ROOT, 'lecture-notes', 'videos.tex'), 'w', encoding='utf8') as f:
        f.write('% Generated by tools/transcripts.py: YouTube ID of every video segment (lecture@part)\n')
        for r in rows:
            f.write(f"\\tsvideo{{{r['lecture']}@{r['part']}}}{{{r['id']}}} % {r['part_title']}\n")

    missing = []
    for r in rows:
        if r.get('override'):
            continue
        raw = glob.glob(os.path.join(MAT, 'transcripts', 'raw', f"{r['index']:03d}-*.json3"))
        if not raw:
            missing.append(r['index'])
            continue
        out = os.path.join(MAT, 'transcripts', f"L{r['lecture']:02d}-P{r['part']:02d}.txt")
        with open(out, 'w', encoding='utf8') as f:
            f.write(f"Lec {r['lecture']}: {r['lecture_title']} | Part {r['part']}: {r['part_title']}"
                    f" | https://youtu.be/{r['id']} | {mmss(r['duration'] * 1000)}\n")
            for t, text in caption_lines(raw[0]):
                f.write(f'{mmss(t)} {text}\n')
    print(f'{len(rows)} segments, {len(rows) - len(missing)} transcripts written'
          + (f', missing: {missing}' if missing else ''))


if __name__ == '__main__':
    main()
